export const jatimWilayah: Record<string, Record<string, string[]>> = {
  Pacitan: {
    Arjosari:      ["Arjosari", "Borang", "Gayuhan", "Gegeran", "Gembong", "Gunungsari", "Jatimalang", "Jetis Kidul", "Karanggede", "Karangrejo", "Kedungbendo", "Mangunharjo", "Mlati", "Pagerejo", "Pagutan", "Sedayu", "Temon", "Tremas"],
    Donorojo:      ["Belah", "Cemeng", "Donorojo", "Gedompol", "Gendaran", "Kalak", "Klepu", "Sawahan", "Sekar", "Sendang", "Sukodono", "Widoro"],
    Kebonagung:    ["Banjarjo", "Gawang", "Gembuk", "Kalipelus", "Karanganyar", "Karangnongko", "Katipugal", "Kebonagung", "Ketepung", "Ketro", "Klesem", "Mantren", "Plumbungan", "Punjung", "Purwoasri", "Sanggrahan", "Sidomulyo", "Wonogondo", "Worawari"],
    Nawangan:      ["Gondang", "Jetislor", "Mujing", "Nawangan", "Ngromo", "Pakisbaru", "Penggung", "Sempu", "Tokawi"],
    Pacitan:       ["Arjowinangun", "Bangunsari", "Banjarsari", "Bolosingo", "Kayen", "Kelurahan Baleharjo", "Kelurahan Pacitan", "Kelurahan Ploso", "Kelurahan Pucangsewu", "Kelurahan Sidoharjo", "Kembang", "Menadi", "Mentoro", "Nanggungan", "Ponggok", "Purworejo", "Sambong", "Sedeng", "Semanten", "Sirnoboyo", "Sukoharjo", "Sumberharjo", "Tambakrejo", "Tanjungsari", "Widoro"],
    Pringkuku:     ["Candi", "Dadapan", "Dersono", "Glinggangan", "Jlubang", "Ngadirejan", "Pelem", "Poko", "Pringkuku", "Sobo", "Sugihwaras", "Tamanasri", "Watu Karung"],
    Punung:        ["Bomo", "Gondosari", "Kebonsari", "Kendal", "Mantren", "Mendolo Kidul", "Mendolo Lor", "Piton", "Ploso", "Punung", "Sooka", "Tinatar", "Wareng"],
    Sudimoro:      ["Gunung Rejo", "Karang Mulyo", "Ketanggung", "Klepu", "Pager Kidul", "Pager Lor", "Sembowo", "Sudimoro", "Sukorejo", "Sumber Rejo"],
    Tegalombo:     ["Gedangan", "Gemaharjo", "Kasihan", "Kebondalem", "Kemuning", "Ngreco", "Ploso", "Pucangombo", "Tahunan", "Tahunan Baru", "Tegalombo"],
    Tulakan:       ["Bubakan", "Bungur", "Gasang", "Jatigunung", "Jetak", "Kalikuning", "Ketro", "Kluwih", "Losari", "Ngile", "Nglaran", "Ngumbul", "Padi", "Tulakan", "Wonoanti", "Wonosidi"],
    Bandar:        ["Bandar", "Bangunsari", "Jeruk", "Kledung", "Ngunut", "Petungsinarang", "Tumpuk", "Watupatok"],
    Ngadirojo:     ["Bodag", "Bogoharjo", "Cangkring", "Cokrokembang", "Hadiluwih", "Hadiwarno", "Ngadirojo", "Nogosari", "Pagerejo", "Sidomulyo", "Tanjung Lor", "Tanjungpuro", "Wiyoro", "Wonoasri", "Wonodadi Kulon"],
  },
  Trenggalek: {
    Bendungan:     ["Botoputih", "Depok", "Dompyong", "Masaran", "Sengon", "Srabah", "Sumurup", "Surenlor"],
    Dongko:        ["Cakul", "Dongko", "Ngerdani", "Nglebo", "Pandean", "Petung", "Pringapus", "Salamwates", "Siki", "Sumberbening", "Watuagung"],
    Durenan:       ["Baruharjo", "Durenan", "Gador", "Gamping", "Kamulan", "Karanganom", "Karanganyar", "Kendalrejo", "Malasan", "Ngadisuko", "Pakis", "Pandean", "Panggungsari", "Semarum", "Sumberejo", "Sumbergayam"],
    Gandusari:     ["Gandusari", "Jajar", "Karanganyar", "Krandegan", "Melis", "Ngrayung", "Sukorame", "Sukorejo", "Widoro", "Wonoanti", "Wonorejo"],
    Kampak:        ["Bendoagung", "Bogoran", "Karangrejo", "Ngadimulyo", "Senden", "Sugihan", "Timahan"],
    Karangan:      ["Buluagung", "Jati", "Jatiprahu", "Karangan", "Kayen", "Kedungsigit", "Kerjo", "Ngentrong", "Salamrejo", "Sukowetan", "Sumber", "Sumberingin"],
    Munjungan:     ["Bangun", "Bendoroto", "Besuki", "Craken", "Karangturi", "Masaran", "Munjungan", "Ngulungkulon", "Ngulungwetan", "Sobo", "Tawing"],
    Panggul:       ["Banjar", "Barang", "Besuki", "Bodag", "Depok", "Gayam", "Karangtengah", "Kertosono", "Manggis", "Nglebeng", "Ngrambingan", "Ngrencak", "Panggul", "Sawahan", "Tangkil", "Terbis", "Wonocoyo"],
    Pogalan:       ["Bendorejo", "Gembleb", "Kedunglurah", "Ngadirejo", "Ngadirenggo", "Ngetal", "Ngulankulon", "Ngulanwetan", "Pogalan", "Wonocoyo"],
    Pule:          ["Joho", "Jombok", "Karanganyar", "Kembangan", "Pakel", "Pule", "Puyung", "Sidomulyo", "Sukokidul", "Tanggaran"],
    Suruh:         ["Gamping", "Mlinjon", "Nglebo", "Ngrandu", "Puru", "Suruh", "Wonokerto"],
    Trenggalek:    ["Dawuhan", "Karangsoko", "Kelurahan Kelutan", "Kelurahan Ngantru", "Kelurahan Sumbergedong", "Kelurahan Surodakan", "Kelurahan Tamanan", "Ngares", "Parakan", "Rejowinangun", "Sambirejo", "Sukosari", "Sumberdadi"],
    Tugu:          ["Banaran", "Dermosari", "Duren", "Gading", "Gondang", "Jambu", "Ngepeh", "Nglinggis", "Nglongsor", "Prambon", "Pucanganak", "Sukorejo", "Tegaren", "Tumpuk", "Winong"],
    Watulimo:      ["Dukuh", "Gemaharjo", "Karanggandu", "Karanganyar", "Margomulyo", "Ngadimulyo", "Ngembel", "Pakel", "Prigi", "Sawahan", "Slawe", "Tasikmadu", "Watuagung", "Watulimo"],
  },
  Magetan: {
    Barat:         ["Bangunasri", "Banjarejo", "Blaran", "Bogorejo", "Jonggrang", "Karangsono", "Kelurahan Mangge", "Kelurahan Tebon", "Klagen", "Manjung", "Ngumpul", "Panggung", "Purwodadi", "Rejomulyo"],
    Bendo:         ["Belotan", "Bulak", "Bulugledeg", "Carikan", "Dukuh", "Duwet", "Kelurahan Bendo", "Kinandang", "Kleco", "Kledokan", "Lemahbang", "Pingkuk", "Setren", "Soco", "Tanjung", "Tegalarum"],
    Karas:         ["Botok", "Geplak", "Ginuk", "Jungke", "Karas", "Kuwon", "Sobontoro", "Sumursongo", "Taji", "Temboro", "Temenggungan"],
    Kartoharjo:    ["Bayem Taman", "Bayem Wetan", "Gunungan", "Jajar", "Jeruk", "Karangmojo", "Kartoharjo", "Klurahan", "Mrahu", "Ngelang", "Pencol", "Sukowidi"],
    Kawedanan:     ["Balerejo", "Bogem", "Garon", "Genengan", "Giripurno", "Jambangan", "Karangrejo", "Kelurahan Kawedanan", "Kelurahan Rejosari", "Kelurahan Sampung", "Mangunrejo", "Mojorejo", "Ngadirejo", "Ngentep", "Ngunut", "Pojok", "Selorejo", "Sugihrejo", "Tladan", "Tulung"],
    Lembeyan:      ["Dukuh", "Kediren", "Kedungpanji", "Kelurahan Lembeyan Kulon", "Krowe", "Lembeyan Wetan", "Nguri", "Pupus", "Tapen", "Tunggur"],
    Magetan:       ["Baron", "Candirejo", "Kelurahan Bulukerto", "Kelurahan Kebonagung", "Kelurahan Kepolorejo", "Kelurahan Magetan", "Kelurahan Mangkujayan", "Kelurahan Selosari", "Kelurahan Sukowinangun", "Kelurahan Tambran", "Kelurahan Tawanganom", "Purwosari", "Ringinagung", "Tambakrejo"],
    Maospati:      ["Gulun", "Kelurahan Kraton", "Kelurahan Maospati", "Kelurahan Mranggen", "Klagen Gambiran", "Malang", "Ngujung", "Pandeyan", "Pesu", "Ronowijayan", "Sempol", "Sugihwaras", "Sumberejo", "Suratmajan", "Tanjungsepreh"],
    Ngariboyo:     ["Baleasri", "Balegondo", "Bangsri", "Banjarejo", "Banjarpanjang", "Banyudono", "Mojopurno", "Ngariboyo", "Pendem", "Selopanggung", "Selotinatah", "Sumberdukun"],
    Panekan:       ["Banjarejo", "Bedagung", "Cepoko", "Jabung", "Kelurahan Panekan", "Manjung", "Milangasri", "Ngiliran", "Rejomulyo", "Sidowayah", "Sukowidi", "Sumberdodol", "Tanjungsari", "Tapak", "Terung", "Turi", "Wates"],
    Parang:        ["Bungkuk", "Joketro", "Kelurahan Parang", "Krajan", "Mategal", "Ngaglik", "Nglopang", "Ngunut", "Pragak", "Sayutan", "Sundul", "Tamanarum", "Trosono"],
    Plaosan:       ["Bogoarum", "Bulugunung", "Buluharjo", "Dadi", "Kelurahan Plaosan", "Kelurahan Sarangan", "Ngancar", "Nitikan", "Pacalan", "Plumpung", "Puntukdoro", "Randugede", "Sendangagung", "Sidomukti", "Sumberagung", "Wonomulyo"],
    Poncol:        ["Cileng", "Genilangit", "Gonggang", "Janggan", "Kelurahan Alastuwo", "Plangkrongan", "Poncol", "Sombo"],
    Sidorejo:      ["Campursari", "Durenan", "Getasanyar", "Kalang", "Sambirobyong", "Sidokerto", "Sidomulyo", "Sidorejo", "Sumbersawit", "Widorokandang"],
    Takeran:       ["Duyung", "Jatisari", "Jomblang", "Kelurahan Takeran", "Kepuhrejo", "Kerang", "Kerik", "Kiringan", "Kuwonharjo", "Madigondo", "Sawojajar", "Tawangrejo", "Waduk"],
    Karangrejo:    ["Baluk", "Gebyok", "Gondang", "Grabahan", "Karangrejo", "Kauman", "Manisrejo", "Mantren", "Maron", "Patihan", "Pelem", "Prampelan", "Sambirembe"],
    Nguntoronadi:  ["Driyorejo", "Gorang-Gareng", "Kenongomulyo", "Nguntoronadi", "Petungrejo", "Purworejo", "Semen", "Simbatan", "Sukowidi"],
    Sukomoro:      ["Bandar", "Bibis", "Bogem", "Bulu", "Kalangketi", "Kedungguwo", "Kembangan", "Kentangan", "Pojoksari", "Sukomoro", "Tamanan", "Tambakmas", "Tinap", "Truneng"],
  },
  Ponorogo: {
    Babadan:       ["Babadan", "Bareng", "Cekok", "Gupolo", "Japan", "Kelurahan Kadipaten", "Kelurahan Kertosari", "Kelurahan Patihan Wetan", "Lembah", "Ngunut", "Polorejo", "Pondok", "Purwosari", "Sukosari", "Trisono"],
    Badegan:       ["Badegan", "Bandaralim", "Biting", "Dayakan", "Kapuran", "Karangan", "Karangjoho", "Tanjunggunung", "Tanjungrejo", "Watubonang"],
    Balong:        ["Bajang", "Balong", "Bulak", "Bulukidul", "Dadapan", "Jalen", "Karangan", "Karangmojo", "Karangpatihan", "Muneng", "Ngampel", "Ngasinan", "Ngendut", "Ngraket", "Ngumpul", "Pandak", "Purworejo", "Sedarat", "Singkil", "Sumberejo", "Tatung", "Temon"],
    Bungkal:       ["Bancar", "Bedikulon", "Bediwetan", "Bekare", "Belang", "Bungkal", "Bungu", "Kalisat", "Ketonggo", "Koripan", "Kunti", "Kupuk", "Kwajon", "Munggu", "Nambak", "Padas", "Pager", "Pelem", "Sambilawang", "Taji"],
    Jambon:        ["Blembem", "Bringinan", "Bulu Lor", "Jambon", "Jonggol", "Karang Lokidul", "Krebet", "Menang", "Poko", "Pulosari", "Sendang", "Sidoharjo", "Srandil"],
    Jenangan:      ["Jenangan", "Jimbe", "Kelurahan Setono", "Kelurahan Singosaren", "Kemiri", "Mrican", "Nglayang", "Ngrupit", "Panjeng", "Paringan", "Pintu", "Plalangan", "Sedah", "Semanding", "Sraten", "Tanjung Sari", "Wates"],
    Jetis:         ["Coper", "Jetis", "Josari", "Karanggebang", "Kradenan", "Kutukulon", "Kutuwetan", "Mojomati", "Mojorejo", "Ngasinan", "Tegalsari", "Turi", "Winong", "Wonoketro"],
    Mlarak:        ["Bajang", "Candi", "Gandu", "Gontor", "Jabung", "Joresan", "Kaponan", "Mlarak", "Nglumpang", "Ngrukem", "Serangan", "Siwalan", "Suren", "Totokan", "Tugu"],
    Ngebel:        ["Gondowido", "Ngebel", "Ngrogung", "Pupus", "Sahang", "Sempu", "Talun", "Wagirlor"],
    Ngrayun:       ["Baosankidul", "Baosanlor", "Binade", "Cepoko", "Gedangan", "Mrayan", "Ngrayun", "Selur", "Sendang", "Temon", "Wonodadi"],
    Ponorogo:      ["Kelurahan Bangunsari", "Kelurahan Banyudono", "Kelurahan Beduri", "Kelurahan Brotonegaran", "Kelurahan Cokromenggalan", "Kelurahan Jingglong", "Kelurahan Kauman", "Kelurahan Keniten", "Kelurahan Kepatihan", "Kelurahan Mangkujayan", "Kelurahan Nologaten", "Kelurahan Paju", "Kelurahan Pakunden", "Kelurahan Pinggirsari", "Kelurahan Purbosuman", "Kelurahan Surodikraman", "Kelurahan Taman Arum", "Kelurahan Tambakbayan", "Kelurahan Tonatan"],
    Pudak:         ["Banjarjo", "Bareng", "Krisik", "Pudak Kulon", "Pudak Wetan", "Tambang"],
    Pulung:        ["Banaran", "Bedrug", "Bekiring", "Karangpatihan", "Kesugihan", "Munggung", "Patik", "Plunturan", "Pomahan", "Pulung", "Pulung Merdiko", "Serag", "Sidoharjo", "Singgahan", "Tegalrejo", "Wagirkidul", "Wayang", "Wotan"],
    Sambit:        ["Bancangan", "Bangsalan", "Bedingin", "Beji", "Besuki", "Bulu", "Campurejo", "Campursari", "Gajah", "Jrakah", "Kemuning", "Maguwan", "Ngadisanan", "Nglewan", "Sambit", "Wilangan", "Wringinanom"],
    Sampung:       ["Carang Rejo", "Gelangkulon", "Glinggang", "Jenangan", "Karang Waluh", "Kunti", "Nglurup", "Pagerukir", "Pohijo", "Ringin Putih", "Sampung", "Tulung"],
    Sawoo:         ["Bondrang", "Grogol", "Ketro", "Kori", "Ngindeng", "Pangkal", "Prayungan", "Sawoo", "Sriti", "Temon", "Tempuran", "Tugurejo", "Tumpakpelem", "Tumpuk"],
    Siman:         ["Beton", "Brahu", "Demangan", "Jarak", "Kelurahan Mangunsuman", "Kelurahan Ronowijayan", "Kepuh Rubuh", "Madusari", "Manuk", "Ngabar", "Patihan Kidul", "Pijeran", "Prawoto", "Ronosentanan", "Sawuh", "Sekaran", "Siman", "Tajug", "Tamanan", "Tranjang", "Trinitisan"],
    Slahung:       ["Broto", "Caluk", "Crabak", "Duri", "Galak", "Gombang", "Gundik", "Janti", "Jebeng", "Kambeng", "Menggare", "Mojopitu", "Nailan", "Ngilo-Ilo", "Ngloning", "Plancungan", "Senepo", "Simo", "Slahung", "Truneng", "Tugurejo", "Wates", "Wonokarti", "Wonovojo"],
    Sooko:         ["Bedoho", "Jurug", "Klepu", "Ngadirojo", "Sooko", "Suru"],
    Sukorejo:      ["Bangunrejo", "Gandukepuh", "Gegeran", "Gelanglor", "Golan", "Kalimalang", "Karanglolor", "Kedung Banteng", "Kranggan", "Lengkong", "Morosari", "Nambangrejo", "Nampan", "Prajegan", "Serangan", "Sidorejo", "Sragi", "Sukorejo", "Tapakrejo", "Tulung"],
    Kauman:        ["Bringin", "Carat", "Ciluk", "Gabel", "Kauman", "Maron", "Nglarangan", "Ngrandu", "Nongkodono", "Pengkol", "Plosojenar", "Semanding", "Somoroto", "Sukosari", "Tegalombo"],
  },
  Ngawi: {
    Geneng:        ["Baderan", "Dempel", "Geneng", "Kasreman", "Keniten", "Keras Wetan", "Kersikan", "Kersoharjo", "Klampisan", "Klitik", "Sidorejo", "Tambakromo", "Tepas"],
    Gerih:         ["Gerih", "Guyung", "Keras Kulon", "Randusongo", "Widodaren"],
    Jogorogo:      ["Brubuh", "Dawung", "Girimulyo", "Jaten", "Jogorogo", "Kletekan", "Kuncen", "Macanan", "Ngrayudan", "Soco", "Talang", "Tanjungsari", "Umbulrejo"],
    Karangjati:    ["Brangol", "Campur Asri", "Danguk", "Dungmiri", "Gempol", "Jatipuro", "Karangjati", "Legundi", "Ploso Lor", "Puhti", "Rejomulyo", "Rejuno", "Ringin Anom", "Sawo", "Sembung", "Sidokerto", "Sidorejo"],
    Kasreman:      ["Cangakan", "Gunungsari", "Jatirejo", "Karang Malang", "Kasreman", "Kiyonten", "Lego Kulon", "Tawun"],
    Kedunggalar:   ["Bangunrejo Kidul", "Begal", "Gemarang", "Jati Gembol", "Jenggrik", "Katikan", "Kawu", "Kedunggalar", "Pelang Kidul", "Pelang Lor", "Wonokerto", "Wonorejo"],
    Kendal:        ["Dadapan", "Gayam", "Karanggupito", "Karangrejo", "Kendal", "Majasem", "Patalan", "Ploso", "Sidorejo", "Simo"],
    Kwadungan:     ["Banget", "Budug", "Dinden", "Jenangan", "Karangsono", "Kendung", "Kwadungan", "Mojomanis", "Pojok", "Purwosari", "Simo", "Sumengko", "Tirak", "Waruk Kalong"],
    Mantingan:     ["Jatimulyo", "Kedungharjo", "Mantingan", "Pakah", "Pakis", "Pengkol", "Sambirejo", "Tambak Boyo"],
    Ngawi:         ["Banyu Urip", "Beran", "Grudo", "Jururejo", "Kandangan", "Karang Tengah Prandon", "Karangasri", "Kartoharjo", "Kelurahan Karang Tengah", "Kelurahan Ketanggi", "Kelurahan Margomulyo", "Kelurahan Pelem", "Kerek", "Mangunharjo", "Ngawi", "Watualang"],
    Ngrambe:       ["Babadan", "Cepoko", "Giriharjo", "Hargomulyo", "Krandegan", "Manisharjo", "Mendiro", "Ngrambe", "Pucangan", "Sambirejo", "Setono", "Sidomulyo", "Tawangrejo", "Wakah"],
    Padas:         ["Banjaransari", "Bendo", "Bintoyo", "Kedung Prahu", "Kwadungan Lor", "Munggut", "Pacing", "Padas", "Sambiroto", "Sukowiyono", "Tambakromo", "Tungkulrejo"],
    Pangkur:       ["Babadan", "Gandri", "Ngompro", "Pangkur", "Paras", "Pleset", "Poh Konyal", "Sumber", "Waruk Tengah"],
    Paron:         ["Babadan", "Dawu", "Gelung", "Gentong", "Jambangan", "Jeblogan", "Kebon", "Kedung Putri", "Ngale", "Paron", "Semen", "Sirigan", "Teguhan", "Tempuran"],
    Pitu:          ["Bangunrejo Lor", "Banjarbanggi", "Cantel", "Dumplengan", "Kalang", "Karanggeneng", "Ngancar", "Papungan", "Pitu", "Selopuro"],
    Sine:          ["Gendol", "Girikerto", "Hargosari", "Jagir", "Kauman", "Ketanggung", "Kuniran", "Ngrendeng", "Pandansari", "Pocol", "Sine", "Sumberejo", "Sumbersari", "Tulakan", "Wonosari"],
    Widodaren:     ["Banyu Biru", "Gendingan", "Karang Banyu", "Karanganyar", "Kauman", "Kayutrejo", "Kedunggudel", "Sekar Alas", "Sekar Putih", "Sidolaju", "Sidomakmur", "Walikukun", "Widodaren"],
    Bringin:       ["Bringin", "Dampit", "Dero", "Gandong", "Kenongorejo", "Krompol", "Lego Wetan", "Mojo", "Sumberbening", "Suruh"],
    Karanganyar:   ["Bangunrejo", "Gembol", "Karanganyar", "Mengger", "Pandean", "Sekarjati", "Sriwedari"],
  },
};

export const kabupatenList = Object.keys(jatimWilayah);

export function getKecamatanList(kabupaten: string): string[] {
  return Object.keys(jatimWilayah[kabupaten] ?? {});
}

export function getDesaList(kabupaten: string, kecamatan: string): string[] {
  return jatimWilayah[kabupaten]?.[kecamatan] ?? [];
}
