export const jatimWilayah: Record<string, Record<string, string[]>> = {
  Pacitan: {
    Arjosari:    ["Arjosari", "Borang", "Gayuhan", "Gegeran", "Gembong", "Gunungsari", "Jatimalang", "Jetis Kidul", "Karanggede", "Karangrejo", "Kedungbendo", "Mangunharjo", "Mlati", "Pagutan", "Sedayu", "Temon", "Tremas"],
    Donorojo:    ["Belah", "Cemeng", "Donorojo", "Gedompol", "Gendaran", "Kalak", "Klepu", "Sawahan", "Sekar", "Sendang", "Sukodono", "Widoro"],
    Kebonagung:  ["Banjarjo", "Gawang", "Gembuk", "Kalipelus", "Karanganyar", "Karangnongko", "Katipugal", "Kebonagung", "Ketepung", "Ketro", "Klesem", "Mantren", "Plumbungan", "Punjung", "Purwoasri", "Sanggrahan", "Sidomulyo", "Wonogondo", "Worawari"],
    Nawangan:    ["Gondang", "Jetis Lor", "Mujing", "Nawangan", "Ngromo", "Pakis Baru", "Penggung", "Sempu", "Tokawi"],
    Pacitan:     ["Arjowinangun", "Baleharjo", "Bangunsari", "Banjarsari", "Bolosingo", "Kayen", "Kembang", "Menadi", "Mentoro", "Nanggungan", "Pacitan", "Ploso", "Ponggok", "Pucangsewu", "Purworejo", "Sambong", "Sedeng", "Semanten", "Sidoharjo", "Sirnoboyo", "Sukoharjo", "Sumberharjo", "Tambakrejo", "Tanjungsari", "Widoro"],
    Pringkuku:   ["Candi", "Dadapan", "Dersono", "Glinggangan", "Jlubang", "Ngadirejan", "Pelem", "Poko", "Pringkuku", "Sobo", "Sugihwaras", "Tamanasri", "Watukarung"],
    Punung:      ["Bomo", "Gondosari", "Kebonsari", "Kendal", "Mantren", "Mendolo Kidul", "Mendolo Lor", "Piton", "Ploso", "Punung", "Sooka", "Tinatar", "Wareng"],
    Sudimoro:    ["Gunungrejo", "Karangmulyo", "Ketanggung", "Klepu", "Pager Kidul", "Pager Lor", "Sembowo", "Sudimoro", "Sukorejo", "Sumberejo"],
    Tegalombo:   ["Gedangan", "Gemaharjo", "Kasihan", "Kebondalem", "Kemuning", "Ngreco", "Ploso", "Pucangombo", "Tahunan", "Tahunan Baru", "Tegalombo"],
    Tulakan:     ["Bubakan", "Bungur", "Gasang", "Jatigunung", "Jetak", "Kalikuning", "Ketro", "Ketro Harjo", "Kluwih", "Losari", "Ngile", "Nglaran", "Ngumbul", "Padi", "Tulakan", "Wonoanti", "Wonosidi"],
    Bandar:      ["Bandar", "Bangunsari", "Jeruk", "Kledung", "Ngunut", "Petungsinarang", "Tumpuk", "Watupatok"],
    Ngadirojo:   ["Bodag", "Bogoharjo", "Cangkring", "Cokrokembang", "Hadiluwih", "Hadiwarno", "Ngadirojo", "Nogosari", "Pagerejo", "Sidomulyo", "Tanjung Lor", "Tanjungpuro", "Wiyoro", "Wonoasri", "Wonodadi Kulon", "Wonodadi Wetan", "Wonokarto", "Wonosobo"],
  },
  Trenggalek: {
    Bendungan:   ["Botoputih", "Depok", "Dompyong", "Masaran", "Sengon", "Srabah", "Sumurup", "Suren Lor"],
    Dongko:      ["Cakul", "Dongko", "Ngerdani", "Pandean", "Petung", "Pringapus", "Salam Wates", "Siki", "Sumber Bening", "Watuagung"],
    Durenan:     ["Baruharjo", "Durenan", "Gador", "Kamulan", "Karanganom", "Kendal Rejo", "Malasan", "Ngadisuko", "Pakis", "Pandean", "Panggungsari", "Semarum", "Sumberejo", "Sumbergayam"],
    Gandusari:   ["Gandusari", "Jajar", "Karanganyar", "Krandegan", "Melis", "Ngrayung", "Sukorame", "Sukorejo", "Widoro", "Wonoanti", "Wonorejo"],
    Kampak:      ["Bendoagung", "Bogoran", "Karangrejo", "Ngadimulyo", "Senden", "Sugihan", "Timahan"],
    Karangan:    ["Buluagung", "Jati", "Jatiprahu", "Karangan", "Kayen", "Kedungsigit", "Kerjo", "Ngentrong", "Salamrejo", "Suko Wetan", "Sumber", "Sumberingin"],
    Munjungan:   ["Bangun", "Bendoroto", "Besuki", "Craken", "Karangturi", "Masaran", "Munjungan", "Ngulungkulon", "Ngulungwetan", "Sobo", "Tawing"],
    Panggul:     ["Banjar", "Barang", "Besuki", "Bodag", "Depok", "Gayam", "Karangtengah", "Kertosono", "Manggis", "Nglebeng", "Ngrambingan", "Ngrencak", "Panggul", "Sawahan", "Tangkil", "Terbis", "Wonocoyo"],
    Pogalan:     ["Bendorejo", "Gembleb", "Kedunglurah", "Ngadirejo", "Ngadirenggo", "Ngetal", "Ngulankulon", "Ngulanwetan", "Pogalan", "Wonocoyo"],
    Pule:        ["Joho", "Jombok", "Karanganyar", "Kembangan", "Pakel", "Pule", "Puyung", "Sidomulyo", "Sukokidul", "Tanggaran"],
    Suruh:       ["Gamping", "Mlinjon", "Nglebo", "Ngrandu", "Puru", "Suruh", "Wonokerto"],
    Trenggalek:  ["Dawuhan", "Karangsoko", "Kelutan", "Ngantru", "Ngares", "Parakan", "Rejowinangun", "Sambirejo", "Sukosari", "Sumberdadi", "Sumbergedong", "Surodakan", "Tamanan"],
    Tugu:        ["Banaran", "Dermosari", "Duren", "Gading", "Gondang", "Jambu", "Ngepeh", "Nglinggis", "Nglongsor", "Prambon", "Pucanganak", "Sukorejo", "Tegaren", "Tumpuk", "Winong"],
    Watulimo:    ["Dukuh", "Gemaharjo", "Karanggandu", "Margomulyo", "Ngembel", "Pakel", "Prigi", "Sawahan", "Slawe", "Tasikmadu", "Watuagung", "Watulimo"],
  },
  Magetan: {
    Barat:       ["Bangunasri", "Banjarejo", "Blaran", "Bogorejo", "Jonggrang", "Karangsono", "Klagen", "Mangge", "Manjung", "Ngumpul", "Panggung", "Purwodadi", "Rejomulyo", "Tebon"],
    Bendo:       ["Belotan", "Bendo", "Bulak", "Bulugledeg", "Carikan", "Dukuh", "Duwet", "Kinandang", "Kleco", "Kledokan", "Lemahbang", "Pingkuk", "Setren", "Soco", "Tanjung", "Tegalarum"],
    Karas:       ["Botok", "Geplak", "Ginuk", "Jungke", "Karas", "Kuwon", "Sobontoro", "Sumursongo", "Taji", "Temboro", "Temenggungan"],
    Kartoharjo:  ["Bayem Taman", "Bayem Wetan", "Gunungan", "Jajar", "Jeruk", "Karangmojo", "Kartoharjo", "Klurahan", "Mrahu", "Ngelang", "Pencol", "Sukowidi"],
    Kawedanan:   ["Balerejo", "Bogem", "Garon", "Genengan", "Giripurno", "Jambangan", "Karangrejo", "Kawedanan", "Mangunrejo", "Mojorejo", "Ngadirejo", "Ngentep", "Ngunut", "Pojok", "Rejosari", "Sampung", "Selorejo", "Sugihrejo", "Tladan", "Tulung"],
    Lembeyan:    ["Dukuh", "Kediren", "Kedungpanji", "Krowe", "Lembeyan Kulon", "Lembeyan Wetan", "Nguri", "Pupus", "Tapen", "Tunggur"],
    Magetan:     ["Baron", "Bulukerto", "Candirejo", "Kebonagung", "Kepolorejo", "Magetan", "Mangkujayan", "Purwosari", "Ringinagung", "Selosari", "Sukowinangun", "Tambakrejo", "Tambran", "Tawanganom"],
    Maospati:    ["Gulun", "Klagen Gambiran", "Kraton", "Malang", "Maospati", "Mranggen", "Ngujung", "Pandeyan", "Pesu", "Ronowijayan", "Sempol", "Sugihwaras", "Sumberejo", "Suratmajan", "Tanjungsepreh"],
    Ngariboyo:   ["Baleasri", "Balegondo", "Bangsri", "Banjarejo", "Banjarpanjang", "Banyudono", "Mojopurno", "Ngariboyo", "Pendem", "Selopanggung", "Selotinatah", "Sumberdukun"],
    Panekan:     ["Banjarejo", "Bedagung", "Cepoko", "Jabung", "Manjung", "Milangasri", "Ngiliran", "Panekan", "Rejomulyo", "Sidowayah", "Sukowidi", "Sumberdodol", "Tanjungsari", "Tapak", "Terung", "Turi", "Wates"],
    Parang:      ["Bungkuk", "Joketro", "Krajan", "Mategal", "Ngaglik", "Nglopang", "Ngunut", "Parang", "Pragak", "Sayutan", "Sundul", "Tamanarum", "Trosono"],
    Plaosan:     ["Bogoarum", "Bulugunung", "Buluharjo", "Dadi", "Ngancar", "Nitikan", "Pacalan", "Plaosan", "Plumpung", "Puntukdoro", "Randugede", "Sarangan", "Sendangagung", "Sidomukti", "Sumberagung"],
    Poncol:      ["Alastuwo", "Cileng", "Genilangit", "Gonggang", "Janggan", "Plangkrongan", "Poncol", "Sombo"],
    Sidorejo:    ["Campursari", "Durenan", "Getasanyar", "Kalang", "Sambirobyong", "Sidokerto", "Sidomulyo", "Sidorejo", "Sumbersawit", "Widorokandang"],
    Takeran:     ["Duyung", "Jomblang", "Kepuhrejo", "Kerang", "Kerik", "Kiringan", "Kuwonharjo", "Madigondo", "Sawojajar", "Takeran", "Tawangrejo", "Waduk"],
    Karangrejo:  ["Baluk", "Gebyok", "Gondang", "Grabahan", "Karangrejo", "Kauman", "Manisrejo", "Mantren", "Maron", "Patihan", "Pelem", "Prampelan", "Sambirembe"],
    Nguntoronadi:  ["Driyorejo", "Gorang-Gareng", "Kenongomulyo", "Nguntoronadi", "Petungrejo", "Purworejo", "Semen", "Simbatan", "Sukowidi"],
    Sukomoro:    ["Bandar", "Bibis", "Bogem", "Bulu", "Kalangketi", "Kedungguwo", "Kembangan", "Kentangan", "Pojoksari", "Sukomoro", "Tamanan", "Tambakmas", "Tinap", "Truneng"],
  },
  Ponorogo: {
    Babadan:     ["Babadan", "Bareng", "Cekok", "Gupolo", "Japan", "Kadipaten", "Kertosari", "Lembah", "Ngunut", "Patihan Wetan", "Polorejo", "Pondok", "Purwosari", "Sukosari", "Trisono"],
    Badegan:     ["Badegan", "Bandaralim", "Biting", "Dayakan", "Kapuran", "Karangan", "Karangjoho", "Tanjunggunung", "Tanjungrejo", "Watubonang"],
    Balong:      ["Bajang", "Balong", "Bulak", "Bulukidul", "Dadapan", "Jalen", "Karangan", "Karangmojo", "Karangpatihan", "Muneng", "Ngampel", "Ngendut", "Ngraket", "Ngumpul", "Pandak", "Purworejo", "Sedarat", "Singkil", "Sumberejo", "Tatung"],
    Bungkal:     ["Bancar", "Bedikulon", "Bediwetan", "Bekare", "Belang", "Bungkal", "Bungu", "Kalisat", "Ketonggo", "Koripan", "Kunti", "Kupuk", "Kwajon", "Munggu", "Nambak", "Padas", "Pager", "Pelem", "Sambilawang"],
    Jambon:      ["Blembem", "Bringinan", "Bulu Lor", "Jambon", "Jonggol", "Karanglo Kidul", "Krebet", "Menang", "Poko", "Pulosari", "Sendang", "Sidoharjo", "Srandil"],
    Jenangan:    ["Jenangan", "Jimbe", "Kemiri", "Mrican", "Nglayang", "Ngrupit", "Panjeng", "Paringan", "Pintu", "Plalangan", "Sedah", "Semanding", "Setono", "Singosaren", "Sraten", "Tanjungsari", "Wates"],
    Jetis:       ["Coper", "Jetis", "Josari", "Karanggebang", "Kradenan", "Kutukulon", "Kutuwetan", "Mojomati", "Mojorejo", "Ngasinan", "Tegalsari", "Turi", "Winong", "Wonoketro"],
    Mlarak:      ["Bajang", "Candi", "Gandu", "Gontor", "Jabung", "Joresan", "Kaponan", "Mlarak", "Nglumpang", "Ngrukem", "Serangan", "Siwalan", "Suren", "Totokan", "Tugu"],
    Ngebel:      ["Gondowido", "Ngebel", "Ngrogung", "Pupus", "Sahang", "Sempu", "Talun", "Wagir Lor"],
    Ngrayun:     ["Baosankidul", "Baosanlor", "Binade", "Cepoko", "Gedangan", "Mrayan", "Ngrayun", "Selur", "Sendang", "Temon", "Wonodadi"],
    Ponorogo:    ["Bangunsari", "Banyudono", "Beduri", "Brotonegaran", "Cokromenggalan", "Jingglong", "Kauman", "Keniten", "Kepatihan", "Mangkujayan", "Nologaten", "Paju", "Pakunden", "Pinggirsari", "Purbosuman", "Surodikraman", "Tamanarum", "Tambakbayan", "Tonatan"],
    Pudak:       ["Banjarjo", "Bareng", "Krisik", "Pudak Kulon", "Pudak Wetan", "Tambang"],
    Pulung:      ["Banaran", "Bedrug", "Bekiring", "Karangpatihan", "Kesugihan", "Munggung", "Patik", "Plunturan", "Pomahan", "Pulung", "Pulung Merdiko", "Serag", "Sidoharjo", "Singgahan", "Tegalrejo", "Wagir Kidul", "Wayang", "Wotan"],
    Sambit:      ["Bancangan", "Bangsalan", "Bedingin", "Besuki", "Bulu", "Campurejo", "Campursari", "Gajah", "Jrakah", "Kemuning", "Maguwan", "Ngadisanan", "Nglewan", "Sambit", "Wilangan", "Wringinanom"],
    Sampung:     ["Carangrejo", "Gelangkulon", "Glinggang", "Jenangan", "Karangwaluh", "Kunti", "Nglurup", "Pagerukir", "Pohijo", "Ringinputih", "Sampung", "Tulung"],
    Sawoo:       ["Bondrang", "Grogol", "Ketro", "Kori", "Ngindeng", "Pangkal", "Prayungan", "Sawoo", "Sriti", "Temon", "Tempuran", "Tugurejo", "Tumpakpelem", "Tumpuk"],
    Siman:       ["Beton", "Brahu", "Demangan", "Jarak", "Kepuhrubuh", "Madusari", "Mangunsuman", "Manuk", "Ngabar", "Patihan Kidul", "Pijeran", "Ronosentanan", "Ronowijayan", "Sawuh", "Sekaran", "Siman", "Tajug", "Tranjang"],
    Slahung:     ["Broto", "Caluk", "Crabak", "Duri", "Galak", "Gombang", "Gundik", "Janti", "Jebeng", "Kambeng", "Menggare", "Mojopitu", "Nailan", "Ngilo-ilo", "Ngloning", "Plancungan", "Senepo", "Simo", "Slahung", "Truneng", "Tugurejo", "Wates"],
    Sooko:       ["Bedoho", "Jurug", "Klepu", "Ngadirojo", "Sooko", "Suru"],
    Sukorejo:    ["Bangunrejo", "Gandukepuh", "Gegeran", "Gelanglor", "Golan", "Kalimalang", "Karanglolor", "Kedungbanteng", "Kranggan", "Lengkong", "Morosari", "Nambangrejo", "Nampan", "Prajegan", "Serangan", "Sidorejo", "Sragi", "Sukorejo"],
    Kauman:      ["Bringin", "Carat", "Ciluk", "Gabel", "Kauman", "Maron", "Nglarangan", "Ngrandu", "Nongkodono", "Pengkol", "Plosojenar", "Semanding", "Somoroto", "Sukosari", "Tegalombo", "Tosanan"],
  },
  Ngawi: {
    Geneng:      ["Baderan", "Dempel", "Geneng", "Kasreman", "Keniten", "Keras Wetan", "Kersikan", "Kersoharjo", "Klampisan", "Klitik", "Sidorejo", "Tambakromo", "Tepas"],
    Gerih:       ["Gerih", "Guyung", "Keras Kulon", "Randusongo", "Widodaren"],
    Jogorogo:    ["Brubuh", "Dawung", "Girimulyo", "Jaten", "Jogorogo", "Kletekan", "Macanan", "Ngrayudan", "Soco", "Talang", "Tanjungsari", "Umbulrejo"],
    Karangjati:  ["Brangol", "Campurasri", "Danguk", "Dungmiri", "Gempol", "Jatipuro", "Karangjati", "Legundi", "Ploso Lor", "Puhti", "Rejomulyo", "Rejuno", "Ringin Anom", "Sawo", "Sembung", "Sidokerto", "Sidorejo"],
    Kasreman:    ["Cangakan", "Gunungsari", "Jatirejo", "Karangmalang", "Kasreman", "Kiyonten", "Lego Kulon", "Tawun"],
    Kedunggalar:  ["Bangunrejo Kidul", "Begal", "Gemarang", "Jatigembol", "Jenggrik", "Katikan", "Kawu", "Kedunggalar", "Pelang Kidul", "Pelang Lor", "Wonokerto", "Wonorejo"],
    Kendal:      ["Dadapan", "Gayam", "Karanggupito", "Karangrejo", "Kendal", "Majasem", "Patalan", "Ploso", "Sidorejo", "Simo"],
    Kwadungan:   ["Banget", "Budug", "Dinden", "Jenangan", "Karangsono", "Kendung", "Kwadungan", "Mojomanis", "Pojok", "Purwosari", "Simo", "Sumengko", "Tirak", "Warukkalong"],
    Mantingan:   ["Jatimulyo", "Kedungharjo", "Mantingan", "Pakah", "Pengkol", "Sambirejo", "Tambakboyo"],
    Ngawi:       ["Banyuurip", "Beran", "Grudo", "Jururejo", "Kandangan", "Karang Asri", "Karangtengah", "Karangtengah Prandon", "Kartoharjo", "Kerek", "Ketanggi", "Mangunharjo", "Margomulyo", "Ngawi", "Pelem", "Watualang"],
    Ngrambe:     ["Babadan", "Cepoko", "Giriharjo", "Hargomulyo", "Krandegan", "Manisharjo", "Mendiro", "Ngrambe", "Pucangan", "Sambirejo", "Setono", "Sidomulyo", "Tawangrejo", "Wakah"],
    Padas:       ["Banjaransari", "Bendo", "Bintoyo", "Kedungprahu", "Kwadungan Lor", "Munggut", "Pacing", "Padas", "Sambiroto", "Sukowiyono", "Tambakromo", "Tungkulrejo"],
    Pangkur:     ["Babadan", "Gandri", "Ngompro", "Pangkur", "Paras", "Pleset", "Pohkonyal", "Sumber", "Waruk Tengah"],
    Paron:       ["Babadan", "Dawu", "Gelung", "Gentong", "Jambangan", "Jeblogan", "Kebon", "Kedungputri", "Ngale", "Paron", "Semen", "Sirigan", "Teguhan", "Tempuran"],
    Pitu:        ["Bangunrejo Lor", "Banjarbanggi", "Cantel", "Dumplengan", "Kalang", "Karanggeneng", "Ngancar", "Papungan", "Pitu", "Selopuro"],
    Sine:        ["Gendol", "Girikerto", "Hargosari", "Jagir", "Kauman", "Ketanggung", "Kuniran", "Ngrendeng", "Pandansari", "Pocol", "Sine", "Sumberejo", "Sumbersari", "Tulakan", "Wonosari"],
    Widodaren:   ["Banyubiru", "Gendingan", "Karangbanyu", "Kauman", "Kayutrejo", "Kedunggudel", "Sekaralas", "Sekarputih", "Sidolaju", "Sidomakmur", "Walikukun", "Widodaren"],
    Bringin:     ["Bringin", "Dampit", "Dero", "Gandong", "Kenongorejo", "Krompol", "Lego Wetan", "Mojo", "Sumberbening", "Suruh"],
    Karanganyar:  ["Bangunrejo", "Gembol", "Karanganyar", "Mengger", "Pandean", "Sekarjati", "Sriwedari"],
  },
};

export const kabupatenList = Object.keys(jatimWilayah);

export function getKecamatanList(kabupaten: string): string[] {
  return Object.keys(jatimWilayah[kabupaten] ?? {});
}

export function getDesaList(kabupaten: string, kecamatan: string): string[] {
  return jatimWilayah[kabupaten]?.[kecamatan] ?? [];
}
